name = "workable"
main = "worker.js"
compatibility_date = "2025-02-01"

workers_dev = true

# ----------------------
# Non-secret variables
# ----------------------
[vars]
WORKABLE_SUBDOMAIN = "pearltalent"